# Generated by Django 5.0 on 2023-12-25 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200, null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('dvt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.measurementunit')),
            ],
        ),
        migrations.CreateModel(
            name='ImportGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('import_source', models.CharField(max_length=200, null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('product_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.product')),
            ],
        ),
        migrations.CreateModel(
            name='ExportGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('output_source', models.CharField(max_length=200, null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('product_export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.product')),
            ],
        ),
    ]
